### PR TITLE
gwt gl20 sync: Use one map per object type instead of a big unified map

### PR DESCRIPTION
**Pull request by stefanhaustein**
This is what libgdx does and it seems more efficient and less "over-engineered" than the unified map.

### CODE REVIEW

**Comment by stefanhaustein** [comment]
p.s. Anything I should do in addition to "mvn test"?

**Comment by samskivert** [comment]
I would install this build locally and then build and run the test project:

```
mvn -f tests/pom.xml -Phtml integration-test
```

Then look at all the screens to make sure nothing looks broken. You can compare against Desktop Java by also running:

```
mvn -f tests/pom.xml -Pjava test
```

**Comment by stefanhaustein** [comment]
Thanks! Looks all good!

**Comment by kles4enko** [comment]
Hi, @stefanhaustein! 
Could you, please, provide the  justification for your solution or reasont to change. It's looks funny when you replace the *one* method with for loop with 3-4 methods with same loop just to fix "over engineered"  code. 
What is the root cause for this change?

**Comment by stefanhaustein** [comment]
The main goal is to synchronize with the libgdx variant of this class, where I am also doing changes for the same purpose, e.g: https://github.com/libgdx/libgdx/pull/4162

While this change indeed adds some (trivial) loops, the alternative is to have a secondary dispatch and additional object type management code, which increases overhead and indirection and thus may harm performance and readability. 

Note that the loops are currently more verbose than they need to be -- otherwise the change probably would reduce the total number of lines of code:

    for (int i = 0; i < n; i++) {
      int id = textures.get();
      WebGLTexture texture = this.textures.remove(id);
      gl.deleteTexture(texture);
   }

could be rewritten as 

    for (int i = 0; i < n; i++) {
      gl.deleteTexture(this.textures.remove(textures.get()));
   }

I am avoiding shortening right now because I wanted to get to a consistent change with minimal changes on both sides -- before doing any more advanced cleanup in sync.

**Comment by samskivert** [comment]
LGTM. I agree that the intmaps are much simpler than the old megamap, and likely faster.

Hopefully the few tabs that snuck in will go away once you've got things in sync. I'm pretty sure libGDX uses spaces too, rather than tabs.

**Comment by kles4enko** [comment]
Hm, seems I missed main changes at night. Sorry. 
It is better, totally agree.

**Pull request merged**
